describe('Product Checkout Test', () => {
	before(function() {
		cy.visit('https://store.luminskin.com/products')
        cy.clearCookies({ log: true})
        cy.clearLocalStorage('my item',{log: true})
		cy.wait(5000)
	}) 

	it('should select a products,add to cart and ship', () => {
		cy.xpath('//div[2]/div/div/a/a/h2').scrollIntoView()
		cy.xpath('//div[2]/div/div/a/a/h2').click()
	    cy.xpath('//div[2]/div/button').scrollIntoView()
		cy.wait(3000)
		cy.xpath('//div[2]/div/button').click()
		cy.get('.checkout-btn').click()
		cy.get('h5').should('be.visible')
		cy.get('h5').contains("YOUR CART")
		cy.get('h6').should('be.visible')
		cy.get('h6').contains("Modern Bathroom Set")
		cy.xpath('//button[2]').click()
		cy.wait(5000)
		cy.xpath('//p').should('be.visible')
		cy.wait(5000)
		cy.get('#field-7').type('jamesfowler@yopmail.com')
		cy.get('#field-8').type('James')
		cy.get('#field-9').type('Fowler')
		cy.get('#field-10').type('Medson way road 3')
		cy.get('#field-11').type('BLK 5')
		cy.xpath('//button/p').scrollIntoView()
		cy.get('#field-12').type('San antonio')
		cy.xpath('//div[2]/div/div/select').select('Texas')
		cy.get('#field-14').type(77449)
		cy.get('#field-16').type(7138510738)
		cy.xpath('//button/p').click()
		cy.wait(5000)
		cy.xpath('//p').should('be.visible')
		cy.xpath('//p').contains("Shipping Address Confirmation")
       
	})
})